Repository AlexanderAsprilla98/Tournament-Management-App, pull requests merged in 2025-01, with the labels that each got.

#37 Enhance layout and styles for improved user experience
  .gitignore
  Dockerfile
  Torneo_RepoAlexander.sln
  app/Torneo.App/Torneo.App.Consola/Torneo.App.Consola.csproj
  app/Torneo.App/Torneo.App.Dominio/Torneo.App.Dominio.csproj
  app/Torneo.App/Torneo.App.Frontend/Areas/Identity/Pages/Account/Login.cshtml
  app/Torneo.App/Torneo.App.Frontend/Areas/Identity/Pages/Account/Login.cshtml.cs
  app/Torneo.App/Torneo.App.Frontend/Areas/Identity/Pages/Account/Logout.cshtml
  app/Torneo.App/Torneo.App.Frontend/Areas/Identity/Pages/Account/Logout.cshtml.cs
  app/Torneo.App/Torneo.App.Frontend/Areas/Identity/Pages/Account/Register.cshtml
  app/Torneo.App/Torneo.App.Frontend/Areas/Identity/Pages/Account/Register.cshtml.cs
  app/Torneo.App/Torneo.App.Frontend/Pages/DTs/Create.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/DTs/Edit.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Equipos/Create.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Equipos/Edit.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Error.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Index.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Jugadores/Create.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Jugadores/Edit.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Municipios/Create.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Municipios/Edit.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Partidos/Create.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Partidos/Edit.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Posiciones/Create.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Posiciones/Edit.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Privacy.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Shared/_Layout.cshtml
  app/Torneo.App/Torneo.App.Frontend/Pages/Shared/_Layout.cshtml.css
  app/Torneo.App/Torneo.App.Frontend/Pages/Shared/_LoginPartial.cshtml
  app/Torneo.App/Torneo.App.Frontend/Program.cs
  app/Torneo.App/Torneo.App.Frontend/Torneo.App.Frontend.csproj
  app/Torneo.App/Torneo.App.Frontend/wwwroot/css/site.css
  app/Torneo.App/Torneo.App.Frontend/wwwroot/favicon.ico
  app/Torneo.App/Torneo.App.Persistencia/DataContext.cs
  app/Torneo.App/Torneo.App.Persistencia/Torneo.App.Persistencia.csproj
Labels: enhancement, frontend

#28 Corrección del error en la edición de entidades con datos duplicados
  .github/workflows/qa_torneofutbolapp-qa.yml
  Dockerfile
  app/Torneo.App/Torneo.App.Frontend/Pages/Equipos/Create.cshtml.cs
  app/Torneo.App/Torneo.App.Frontend/Pages/Equipos/Edit.cshtml.cs
  app/Torneo.App/Torneo.App.Frontend/Pages/Jugadores/Create.cshtml.cs
  app/Torneo.App/Torneo.App.Frontend/Pages/Jugadores/Edit.cshtml.cs
  app/Torneo.App/Torneo.App.Frontend/Pages/Municipios/Create.cshtml.cs
  app/Torneo.App/Torneo.App.Frontend/Pages/Municipios/Edit.cshtml.cs
  app/Torneo.App/Torneo.App.Frontend/Pages/Partidos/Edit.cshtml.cs
  app/Torneo.App/Torneo.App.Frontend/Pages/Posiciones/Create.cshtml.cs
  app/Torneo.App/Torneo.App.Frontend/Pages/Posiciones/Edit.cshtml.cs
  app/Torneo.App/Torneo.App.Persistencia/AppRepositorios/IRepositorioMunicipio.cs
  app/Torneo.App/Torneo.App.Persistencia/AppRepositorios/IRepositorioPosicion.cs
  app/Torneo.App/Torneo.App.Persistencia/AppRepositorios/RepositorioDT.cs
  app/Torneo.App/Torneo.App.Persistencia/AppRepositorios/RepositorioJugador.cs
  app/Torneo.App/Torneo.App.Persistencia/AppRepositorios/RepositorioMunicipio.cs
  app/Torneo.App/Torneo.App.Persistencia/AppRepositorios/RepositorioPartido.cs
  app/Torneo.App/Torneo.App.Persistencia/AppRepositorios/RepositorioPosicion.cs
Labels: bug, backend

#38 dev
  .github/workflows/main.yml
  .gitignore
  Dockerfile
  Torneo.App/Torneo.App.Frontend/secrets.json
  docker-compose.yml
Labels: bug, enhancement, CI/CD
